# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 09:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20170313_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='users_likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
